spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quartz?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  #mvc:
  #    view:
   #     prefix: /static/
mybatis: 
  mapper-locations:
  - classpath:com/example/demo/dao/mapper/*.xml
  type-aliases-package: com.example.demo.entity
logging:
  config: classpath:log4j2.xml
  # 打印sql
  level:
    com.example.demo.dao: debug


    